server:
  port: 8888

logging:
  path: logs
  file: mylog.log
spring:
  application:
    name: myTest
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_autoTest
    username: root
    password: 4512554
mybatis:
  type-aliases-package: com.course.model
  mapper-locations:
   - mapper/*


